version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=azinox21'
      - 'POSTGRES_DB=olx_clone_db'

  app:
    build: ./
    container_name: 'java-olx-app'
    ports:
      - "8080:8080"