name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Maven
        run: |
          curl -fsSL https://apache.osuosl.org/maven/maven-3/3.11.0/binaries/apache-maven-3.11.0-bin.tar.gz -o maven.tar.gz
          tar -xf maven.tar.gz
          export PATH=$(pwd)/apache-maven-3.11.0/bin:$PATH
          mvn --version

      - name: Install JDK 17
        run: sudo apt-get install -y openjdk-17-jdk


      - name: Package
        run: mvn package

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: docker push vercetti88/olxappimage:commit1

      - name: Log into DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: docker push vercetti88/olxappimage:commit1
